openapi: 3.0.1
info:
  title: Schema Service
  description: |
    Manage the mixins schemas for miscellaneous types.
  contact:
    email: documentation@emporix.com
  version: ''
servers:
  - url: 'https://api.emporix.io'
paths:
  '/schema/{tenant}/schemas':
    post:
      tags:
        - Schema
      summary: Creating a schema
      description: |
        Creates a schema entity and generates json-schema representation which is then uploaded to cloudinary repository.

      operationId: POST-schema-create-schema
      security:
        - OAuth2:
            - schema.schema_manage
    get:
      summary: Retrieving all schemas
      description: |-
        Retrieves all schemas. You can filter the results with query parameters.
      tags:
        - Schema
      operationId: GET-schema-retrieve-schemas
  '/schema/{tenant}/schemas/{id}':
    get:
      summary: Retrieving a schema
      description: |-
        Retrieves a single schema.
      tags:
        - Schema
      operationId: GET-schema-retrieve-schema
    delete:
      summary: Deleting a schema
      description: |-
        Deletes a single schema. It deletes just a database entry. The cloudinary reference file remains untouched.
      tags:
        - Schema
      operationId: DELETE-schema-remove-schema
      security:
        - OAuth2:
            - schema.schema_manage
    put:
      summary: Updating a schema
      description: |-
        Updates a single schema. Each update releases a new version of json schema file.

      tags:
        - Schema
      operationId: PUT-schema-update-schema
      security:
        - OAuth2:
            - schema.schema_manage
  '/schema/{tenant}/schemas/{id}/types':
    put:
      summary: Updating types of a schema
      description: |-
        Updates assigned types to the schema. It's allowed to change the assigned types to the newest schema as well as to the previous versions of the schema. This operation does not generate a new version of the schema.

      tags:
        - Type
      operationId: PUT-schema-update-schema-types
      security:
        - OAuth2:
            - schema.schema_manage
  '/schema/{tenant}/schemas/file':
    post:
      tags:
        - Schema
      summary: Providing a file
      description: |
        Validates and parses provided json schema file. When the file is valid, it returns a json which can be used either to create a new schema via POST operation or to update an existing one via PUT operation when all the missing fields are provided. It doesn't create any file and it doesn't crease a database entity.
      operationId: POST-schema-parse-schema-file
  '/schema/{tenant}/types':
    get:
      summary: Retrieving types
      description: |-
        Retrieves types which have at least one schema assigned.
      tags:
        - Type
      operationId: GET-schema-retrieve-schema-types
  '/schema/{tenant}/references':
    post:
      tags:
        - Reference
      summary: Creating a reference
      description: |
        Creates a reference entity and uploads provided file to the cloudinary repository.

      operationId: POST-schema-create-reference
      security:
        - OAuth2:
            - schema.schema_manage
    get:
      summary: Retrieving all references
      description: |-
        Retrieves all references. You can filter the results with query parameters.
      tags:
        - Reference
      operationId: GET-schema-retrieve-references
  '/schema/{tenant}/references/{id}':
    get:
      summary: Retrieving a reference
      description: |-
        Retrieves a single reference.
      tags:
        - Reference
      operationId: GET-schema-retrieve-reference
    delete:
      summary: Deleting a reference
      description: |-
        Deletes a single reference. It deletes just a database entry. The cloudinary reference file remains untouched.

      tags:
        - Reference
      operationId: DELETE-schema-remove-reference
      security:
        - OAuth2:
            - schema.schema_manage
    put:
      summary: Updating a reference
      description: |-
        Updates a single reference.

      tags:
        - Reference
      operationId: PUT-schema-update-reference
      security:
        - OAuth2:
            - schema.schema_manage
  '/schema/{tenant}/custom-entities':
    post:
      tags:
        - Custom Schema Type
      summary: Creating a custom schema type
      description: |
        Creates a custom type entity that can be later used for creating custom instances.

        **Note**: When a custom entity type is created, a set of custom scopes is created, which allow managing custom instances of that type.

      operationId: POST-schema-create-custom-schema-type
      security:
        - OAuth2:
            - schema.schema_manage
    get:
      summary: Retrieving all custom schema types
      description: |-
        Retrieves all custom schema types.
      tags:
        - Custom Schema Type
      operationId: GET-schema-retrieve-custom-schema-types
  '/schema/{tenant}/custom-entities/{id}':
    get:
      summary: Retrieving a custom schema type
      description: |-
        Retrieves a single custom schema type by id.
      tags:
        - Custom Schema Type
      operationId: GET-schema-retrieve-custom-schema-type
    delete:
      summary: Deleting a custom schema type
      description: |-
        Deletes a single custom type. This operation will fail if there are schemas or custom instances assigned to this custom type.

        **Note**: Removing a custom entity type does not remove the custom scopes that were created when the type was added. Those scopes remain in the system until you remove them manually, if needed.

      tags:
        - Custom Schema Type
      operationId: DELETE-schema-remove-custom-schema-type
      security:
        - OAuth2:
            - schema.schema_manage
    put:
      summary: Upserting a custom schema type
      description: |-
        Performs the `UPSERT` operation. If a custom schema type with specified ID exists in the system, then it is updated. If it doesn't exist, a new type is created.

        **Note**: When a custom entity type is created, a set of custom scopes is created, which allow managing custom instances of that type.

      tags:
        - Custom Schema Type
      operationId: PUT-schema-upsert-custom-schema-type
      security:
        - OAuth2:
            - schema.schema_manage
  '/schema/{tenant}/custom-entities/{type}/instances':
    post:
      tags:
        - Custom Instance
      summary: Creating a custom instance
      description: |
        Creates a custom instance entity associated with given custom schema type.

      operationId: POST-schema-create-custom-instance
      security:
        - OAuth2:
            - schema.custominstance_manage
            - 'custom.{lowerCaseType}_manage'
            - 'custom.{lowerCaseType}_manage_own'
    get:
      summary: Retrieving all custom instances
      description: |-
        Retrieves all custom instances associated with a specific custom schema type.

      tags:
        - Custom Instance
      operationId: GET-schema-retrieve-custom-instances
      security:
        - OAuth2:
            - schema.custominstance_read
            - 'custom.{lowerCaseType}_read'
            - 'custom.{lowerCaseType}_read_own'
  '/schema/{tenant}/custom-entities/{type}/instances/{id}':
    get:
      summary: Retrieving a custom instance
      description: |-
        Retrieves a single custom instance by id.

      tags:
        - Custom Instance
      operationId: GET-schema-retrieve-custom-instance
      security:
        - OAuth2:
            - schema.custominstance_read
            - 'custom.{lowerCaseType}_read'
            - 'custom.{lowerCaseType}_read_own'
    delete:
      summary: Deleting a custom instance
      description: |-
        Deletes a custom instance.

      tags:
        - Custom Instance
      operationId: DELETE-schema-remove-custom-instance
      security:
        - OAuth2:
            - schema.custominstance_manage
            - 'custom.{lowerCaseType}_manage'
            - 'custom.{lowerCaseType}_manage_own'
    put:
      summary: Upserting a custom instance
      description: |-
        Performs the `UPSERT` operation. If a custom instance with specified ID exists in the system, then it is updated. If it doesn't exist, a new custom instance is created.

      tags:
        - Custom Instance
  '/schema/{tenant}/custom-entities/{type}/instances/bulk':
    post:
      tags:
        - Custom Instance
      summary: Bulk creating custom instances
      description: |
        Creates multiple custom instance entities associated with the given custom schema type in a single request.

        The maximum number of items allowed in the bulk request is 5000.

      operationId: POST-schema-create-custom-instances-bulk
      security:
        - OAuth2:
            - schema.custominstance_manage
            - 'custom.{lowerCaseType}_manage'
            - 'custom.{lowerCaseType}_manage_own'